dbots-pkg/dbots.js

package-lock.json, package.json, typings/index.d.ts
Hey, I made a type definition file for this package: this way every time somebody installs it their editor (if it has a ts engine like VSCode or Atom) will give docs and autocomplete suggestions.
That will work both in regular JavaScript and in TypeScript, where the editor can also correct type errors.
=> Ts definitions

src/Utils/Constants.js
They have updated their API since the code was written, here's the updated version
=> Update botsfordiscord PostFormat

package-lock.json, package.json, src/Interface/BotsForDiscord.js, src/Interface/DiscordBotsGG.js, src/Interface/DiscordBotsOrg.js, src/Interface/Listcord.js, src/Utils/Constants.js, src/Utils/FormatRequest.js
I've done this because snekfetch is a deprecated package: now it's using axios, and so we'll be able to get support if needed.
=> Move from snekfetch to axios

docs/general/services.md, src/Interface/Lists/Blist.js, src/Interface/Lists/DiscordBotsCo.js, src/Interface/Lists/DiscordLabs.js, src/Interface/Lists/DiscordListology.js, src/Interface/Lists/TopCord.js, typings/index.d.ts
=> Add 5 new services

src/Interface/Lists/BotListSpace.js, src/Interface/Lists/BotsForDiscord.js, src/Interface/Lists/BotsOnDiscord.js, src/Interface/Lists/Carbon.js, src/Interface/Lists/DBLista.js, src/Interface/Lists/DiscordAppsDev.js, src/Interface/Lists/DiscordBoats.js, src/Interface/Lists/DiscordBotWorld.js, src/Interface/Lists/DiscordBotsCo.js, src/Interface/Lists/DiscordLabs.js, src/Interface/Lists/DiscordListology.js, src/Interface/Lists/ListMyBots.js, src/Interface/Lists/MythicalBots.js, src/Interface/Lists/SpaceBotsList.js, src/Interface/Lists/TopCord.js, src/Interface/Lists/YABL.js
- Use the no sharding warning consistently
- Add a private tag and a better explanation for DBLista#post
- Fix capitalization in TopCord
- Remove trailing slash in DiscordLabs & DiscordListology's API URL
=> Documentation Cleanup & Small Fixes

docs/general/services.md, src/Interface/Lists/DiscordServices.js, src/Interface/ServiceBase.js, src/Utils/FormatRequest.js, typings/index.d.ts
=> New service: DiscordServices

docs/general/services.md, lib/Interface/Lists/AstroBotList.d.ts, lib/Interface/Lists/AstroBotList.js, package-lock.json, package.json, src/Interface/Lists/AstroBotList.ts
=> New service: AstroBotList

docs/general/services.md, lib/Interface/Lists/InfinityBotList.d.ts, lib/Interface/Lists/InfinityBotList.js, lib/Interface/Service.js, src/Interface/Lists/InfinityBotList.ts, src/Interface/Service.ts, tests/Interface/Service.test.ts
=> feat: add InfinityBotList

docs/general/services.md, lib/Interface/Lists/DiscordBotDirectory.d.ts, lib/Interface/Lists/DiscordBotDirectory.js, src/Interface/Lists/DiscordBotDirectory.ts
=> feat: add DiscordBotDirectory

docs/general/services.md, lib/Interface/Lists/DiscordBotDirectory.d.ts, lib/Interface/Lists/DiscordBotDirectory.js, lib/Interface/Lists/VoidBots.d.ts, lib/Interface/Lists/VoidBots.js, src/Interface/Lists/DiscordBotDirectory.ts, src/Interface/Lists/VoidBots.ts, tests/Interface/Lists/common.test.ts
=> feat: add VoidBots

docs/general/services.md, lib/Interface/Lists/VoidBots.d.ts, lib/Interface/Lists/VoidBots.js, src/Interface/Lists/VoidBots.ts
They're going to require everyone to use the updated API, so updating is necessary before releasing the minor package update.
Ref #58
=> fix: update VoidBots

docs/general/services.md, lib/Interface/Lists/BladeBotList.d.ts, lib/Interface/Lists/BladeBotList.js, src/Interface/Lists/BladeBotList.ts
=> feat: add BladeBotList

docs/general/services.md, lib/Interface/Lists/BladeBotList.d.ts, lib/Interface/Lists/BladeBotList.js, lib/Interface/Lists/Blist.d.ts, lib/Interface/Lists/Blist.js, lib/Interface/Lists/DisTop.d.ts, lib/Interface/Lists/DisTop.js, src/Interface/Lists/BladeBotList.ts, src/Interface/Lists/Blist.ts, src/Interface/Lists/DisTop.ts
=> feat: add DisTop

docs/general/services.md, lib/Interface/Lists/InfinityBotList.d.ts, lib/Interface/Lists/InfinityBotList.js, src/Interface/Lists/InfinityBotList.ts
=> fix: update InfinityBotList

docs/general/services.md, lib/Interface/Lists/Blist.d.ts, lib/Interface/Lists/Blist.js, lib/Interface/Lists/TopCord.d.ts, lib/Interface/Lists/TopCord.js, src/Interface/Lists/Blist.ts, src/Interface/Lists/TopCord.ts
I've been so slow to release v7 that two services updated their APIs 😅
=> Service updates

docs/general/services.md, package-lock.json, package.json, webpack.config.js
Hi, this should fix the security alert regarding `ssri`. I'm not really familiar with webpack, so let me know if this looks good to you.
I've followed webpack's [migration guide](https://webpack.js.org/migrate/5/), and the webpack build scripts works fine. I don't use the bundled version though...
=> Upgrade to webpack v5

README.md
It was pretty noticeable and in probably the most read paragraph of documentation for the project, so I thought I would go ahead and fix it.
=> spelling correction in main readme

package-lock.json, package.json
Reverts dbots-pkg/dbots.js#235
=> Revert "chore(deps-dev): bump typescript from 4.2.4 to 4.3.2"

.github/workflows/test.yml, package-lock.json, src/Interface/Lists/DiscordBotlistEU.ts
I've improved on the discord-botlist.eu class added in #318:
- Endpoints now use the Bearer token format
- Ping and Analytics endpoitns have been added
These changes come not from the official docs, but from the official library: [npm](https://npm.im/@dbleu/node), [GitHub](https://github.com/dbleu/node-library)
@Snazzah could you give it a look before we publish it?
=> Improve discord-botlist.eu

src/Interface/Lists/FatesList.ts
Update to new API version, drop additional endpoints (too many to maintain)
=> fix!(FatesList): update list to new API version

docs/general/services.md, src/Interface/ListIndex.ts, src/Interface/Lists/DList.ts
=> feat: add DList
